# Generated by Django 5.1.2 on 2024-10-24 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_album'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Album',
        ),
    ]
